### ISSUE TITLE
OSError with auto py2exe

### ISSUE THREAD

**Issue by saivineetha1998** [MSLNZ/msl-loadlib#33] opened 2023-02-16 05:46 UTC
Hello
I am using 32 bit dll on 64-bit python. I am converting the py file to exe file using Auto py to exe [https://pypi.org/project/auto-py-to-exe/](url).
I am getting the following error 
![Screenshot (122)](https://user-images.githubusercontent.com/29201889/219279119-92995563-9f84-48fe-b5b2-e01cb1483e2c.png)

There is no error when executing in editor.
How could I solve this issue.

**Comment by jborbely** [comment] 2023-02-16 18:38
I would need more information explaining what your `auto-py-to-exe` settings are, but it looks like you have not bundled the 32-bit server, `server32-windows.exe`, with your exe.

For example, suppose you wanted to convert the following script (called `issue33.py`)

```python
# issue33.py
from msl.loadlib import Client64, Server32

class MyServer(Server32):

    def __init__(self, host, port):
        super().__init__('cpp_lib32.dll', 'cdll', host, port)

    def add(self, a, b):
        # Returns a+b
        return self.lib.add(a, b)

class MyClient(Client64):

    def __init__(self):
        super().__init__(module32=__file__)

    def add(self, a, b):
        return self.request32('add', a, b)

if __name__ == '__main__':
    c = MyClient()
    print(c.add(1, 2))
```

to an exe, you would include these additional files (*NOTE: you need to update the leading ".." with the absolute path to the files*)

![image](https://user-images.githubusercontent.com/4319367/219455952-79809ec7-634c-42ef-a28b-64049b68f289.png)

For this example to work for me, the `auto-py-to-exe` command was
```
pyinstaller --noconfirm --onedir --console --hidden-import "pkgutil" --add-data "../issue33.py;." --add-data "../Lib/site-packages/msl/examples/loadlib/cpp_lib32.dll;." --add-data "../Lib/site-packages/msl/loadlib/server32-windows.exe;msl\loadlib"  "../issue33.py"
```

**Comment by saivineetha1998** [comment] 2023-02-20 04:42
I have added server32-windows.exe in data. Settings in auto-py-to-exe are as below
![Screenshot (123)](https://user-images.githubusercontent.com/29201889/220011112-5e0965c8-df2f-4ad4-ac5c-3611184a12f7.png)

But still I couldn't resolve the issue.

**Comment by jborbely** [comment] 2023-02-20 05:37
Unfortunately, you did not add `server32-windows.exe` to the correct location. You are adding it to the root directory `.` whereas I showed that it must be added to `msl\loadlib` (see screenshot above).

Also, using the _One File_ option can cause additional complications. I recommend that you first use _One Directory_ to demonstrate that you can get it to work in the simpler case and then try _One File_ afterwards (even `auto-py-to-exe` is warning you about this ... _Be careful when using additional files with onefile mode_).

Finally, the example I showed above is runnable, meaning that you are able to run `auto-py-to-exe` on the example `issue33.py` script and configure `auto-py-to-exe` to achieve the same `PyInstaller` command that I had. If you cannot get my minimal example to work then I think you will have difficulties getting yours to work.

**Comment by saivineetha1998** [comment] 2023-02-21 08:13
I have added msl\loadlib. Now I am getting the following error.
Could you help me in resolving this
![Screenshot (127)](https://user-images.githubusercontent.com/29201889/220286102-c077f20d-3f57-47d7-be82-d6d1c1b888f8.png)

**Comment by jborbely** [comment] 2023-02-21 20:18
I modified my example `issue33.py` script to include an encoding test,

```python
# issue33.py
from msl.loadlib import Client64, Server32

class MyServer(Server32):

    def __init__(self, host, port):
        super().__init__('cpp_lib32.dll', 'cdll', host, port)

    def add(self, a, b):
        # Returns a+b
        return self.lib.add(a, b)

    def encode(self, text, encoding):
        return text.encode(encoding).decode(encoding)

class MyClient(Client64):

    def __init__(self):
        super().__init__(module32=__file__)

    def add(self, a, b):
        return self.request32('add', a, b)

    def encode(self, text, encoding):
        return self.request32('encode', text, encoding)

if __name__ == '__main__':
    c = MyClient()
    print(c.add(1, 2))
    print(c.encode('example', 'idna'))
    print('example'.encode('idna').decode('idna'))
```
configured `auto-py-to-exe` to generate the following `PyInstaller` command to build the executable (with the _onefile_ option)
```
pyinstaller --noconfirm --onefile --console --add-data "../Lib/site-packages/msl/loadlib/server32-windows.exe;msl\loadlib" --add-data "../Lib/site-packages/msl/examples/loadlib/cpp_lib32.dll;." --add-data "issue33.py;." --hidden-import "pkgutil"  "issue33.py"
```
and then ran the executable
```
> issue33.exe
3
example
example
```
This verifies that `server32-windows.exe` has the `idna` encoding and the frozen `issue33.py` script has the `idna` encoding.

I cannot reproduce the `LookupError: unknown encoding: idna`, so could you please provide a minimal reproducible example. So far, this issue has nothing to do with `msl-loadlib` so my ability to help can only go so far. You can try adding `import encodings.idna` at the top of your `USB2ANY_Server.py` file, or use a different encoding if possible.

**Comment by saivineetha1998** [comment] 2023-02-24 04:54
It worked after importing encodings.idna in USB2ANY_Server.py file.

Thanks a lot for the help.

**Comment by jborbely** [comment] 2023-02-25 22:25
I'm glad to hear that you found a fix.

I assume that you reopened this issue by accident. I will close it, but please create a new issue if one occurs.

**Closed by jborbely** 2023-02-25 22:25 UTC
